### ISSUE TITLE
[ Feat ]: Add session flash message for new code requests.

### ISSUE THREAD

**Issue by andersr** [dev-xo/remix-auth-totp#24]
Currently, it appears there is no feedback in the UI when a new OTP is requested, ie something like a "New Code Sent" flash message.  

One way to enable this would be to set a session flash message once when a the [TOTP is re-sent](https://github.com/dev-xo/remix-auth-totp/blob/b82e4d0ecf41ac50e8a07e19960d6f9077dafb7a/src/index.ts#L416-L425).

Thoughts?

**Comment by dev-xo** [comment]
Sounds good to me @andersr. 
It'll improve user experience and minimize client-side state management.

Thank you for the feedback!

**Comment by shyamlohar** [comment]
@dev-xo I can help with this. Should I go ahead and send Pull request for same?

**Comment by dev-xo** [comment]
Absolutely, @shyamlohar! Feel free to open a PR on it!

**Comment by mw10013** [comment]
@andersr: The title of your issue seems to focus on new code requests while the body of the issue mentions re-sent codes. New code logic is a bit separated from re-sent code logic. So anything flashy done with re-sent codes would not necessarily appear with new code requests.

Can you walk us through the new code and re-sent code flow that you are trying to achieve and where `remix-auth-totp` is not helpful. Any details on the `/verify` loader/action would be very helpful to see.

We are currently discussing PR #40 which may be relevant and feel free to join the discussion.
