### ISSUE TITLE
[ Feat ] Remove hostUrl from MagicLinkGenerationOptions

### ISSUE THREAD

**Issue by mw10013** [dev-xo/remix-auth-totp#33]
Remove hostUrl from MagicLinkGenerationOptions since it seems unnecessary and may even be a foot gun.

I am struggling to come up with a case where you would want to specify hostUrl explicitly because it would be different from the origin of the request url. If you do specify hostUrl and it is different from the origin of the request url, then the browser will not provide the right cookies to the magic link and you've shot yourself in the foot.

@dev-xo: Please share your thoughts and if you want to proceed, I can move it forward.

**Comment by dev-xo** [comment]
Sounds good to me, @mw10013! As I said before, it's been some time since the magic-link feature and the library has undergone a few updates. Some of the parameters/options added initially might not make sense at all nowadays.

Feel free to go for it. If the tests pass, we are as good as we can be! :)
