### ISSUE TITLE
[ Refactor ] Decomplect handleTOTP() API

### ISSUE THREAD

**Issue by mw10013** [dev-xo/remix-auth-totp#35]
`storeTOTP()` and `handleTOTP()` seem to be CRUD operations. 

`handleTOTP()` seems to combine Read and Update and doesn't do any "processing" as implied by "handle" in its name. It will need a bit of logic to determine if a Read will suffice or an Update is also needed. If `handleTOTP()` where split into `getTOTP()` and `updateTOTP()`, the understanding and implementation is dead simple and one does not have to pause to understand what a `handleTOTP()` does and how it should be implemented.

Removing the setting of `expiresAt` in handleTOTP() may simplify while making more robust.

- `expiresAt` is needed at Create time.
  - On Cloudflare, storing the TOTP in Cloudflare KV is an attractive option and one naturally wants to create the key with an expiration time. If the expiration is not known at Create time and set later, there is the potential to create garbage if `handleTOTP()` not subsequently called after creation due to unpredictable server failure.
  - With a database that has a column for `expiresAt`, the column would need to allow null's if `expiresAt` is not known at Create time. There is the potential to create garbage if `handleTOTP()` is not subsequently called after creation due to unpredictable server failure. The null handling also adds a little complexity to any batch script that cleans up expired totp's.
-  `remix-auth-totp` does not need `expiresAt` from TOTP storage. `expiresAt` appears to be more like metadata at Create time. The application can chose what to do with it at Create time and need never return it to `remix-auth-totp`.

The proposal is to replace `storeTOTP()` and `handleTOTP()` with the following.

```ts
interface TOTP {
  hash: string;
  active: boolan;
  attempts: number;
}

createTOTP(totp: TOTP, expiresAt: Date): void;
getTOTP(hash: string): TOTP;
updateTOTP(hash: string, data: Partial<Omit<TOTP, "hash">>): void;
```

@dev-xo: please share your thoughts.

**Comment by dev-xo** [comment]
Hello @mw10013. As always, thank you for taking the time to look into this.

The initial idea when `handleTotp` was created was to avoid requiring the developer to handle more methods than necessary on Strategy initialization. Therefore, `handleTotp` was defined to manage both **get** and **update** CRUD operations. This approach aimed to reduce the number of methods returned to the developer, although it would have certainly clarified its internal workings, making the mental model simpler to grasp for us the library maintainers.

Regarding `expiresAt`, this was recently added as a means for developers to clean up unused or expired TOTPs. It was a bit of a mental headache because its implementation solely depends on the user database and the need to support types typically used by that databases.

I'm unsure if we could address this in another way.
- How would you delete unused TOTPs from a large database?

I'm okay with removing it or refactoring it in a way that could prevent issues with Cloudflare / Servers if it's not initialized properly.

---

With that said, I will be a bit busy in the following days, but **I'm up for this changes.** Feel free to open a PR with them. You have already proven your expertise, and the library has significantly improved since your last commits.

Again, thank you so much for the time and effort you are putting into this! I hope you are doing this only because you have the time and are enjoying your experience with the library! I wouldn't want you to spend more time on it than necessary.

Thanks again @mw10013!
