### ISSUE TITLE
[ Discussion ] Add support for different OTP sending methods. 

### ISSUE THREAD

**Issue by haus23** [dev-xo/remix-auth-totp#49]
To decouple the discussion within issue #47 i would like to start a discussion her.

Questions:
- How much code is email-related in the existing code base?
- What are possible methods to send a TOTP?

First: imho the only email relevant code is in the simple `_validateEmailDefaults`-Function. Beside that you could to a s/Email/Contact/g replace.

Second:
 - Email needs an Email-Address
 - WhatsApp needs a Phone Number
 - SMS needs a Phone Number
 - ...
 
What about removing the validation of the email in the above mentioned function and leave it up to the client as the sending of the totp is already left up to the client?

So you would just have to find a common field name (contact, address, contactInfo, destination, ...) and decouple the code completely from relaying on an email-Address for this field?

What do you think?

**Comment by dev-xo** [comment]
Hello again, @haus23. We'll need to first deploy the `v3` in order to have some proper talks about the next features/changes we could make.

I would suggest having a look at the code-base to propose proper changes, as we could not answer questions like: _"How much code is email-related in the existing code base?"_.

In any case, if you have the time and would like to adventure yourself into it, and coming up with a Pull Request that we could review and discuss about, feel free to do so. It will be welcomed.

- - -
Closing this for now. It will probably be revisited after `v3` release.

**Comment by dev-xo** [comment]
Hello @shawnmclean. Feel free to propose something or ways to achieve it, and we can look into it. Currently, we are a bit busy with some other projects, but we are up for a discussion and possible implementations!

**Comment by dev-xo** [comment]
I think so, @shawnmclean. At least, probably context can do it for us to use some other services. 
- Wonder if @mw10013 will be able to give a better response.

As I said before, any suggestions on how we could handle this, or a PR, would be more than welcome.
