### ISSUE TITLE
[ Fix ] Security Vulnerability

### ISSUE THREAD

**Issue by ryan0x44** [dev-xo/remix-auth-totp#56]
The secret used to generate the TOTP code is given to the user requesting the code.

If the attacker knows how to decode the information given to them, **the attacker can completely circumvent the login mechanism without requiring access to the email address**. This means the attacker can impersonate any email address/user.

I have built a proof of concept which demonstrates the attack, and have sent this to the package owner.

The fix for this is to encrypt the secret used to generate the TOTP code before sending it to the requesting user.

**Comment by dev-xo** [comment]
Thanks for looking into this, @ryan0x44, also thanks for the DMs on Twitter.

I shared your proof of concept with @mw10013, and we will be back here to discuss it further. Not sure if you got the time to look into opening a PR, otherwise we will look into it with some guidance from your side.

**Comment by dev-xo** [comment]
Renaming until we discuss this further, and the proof of concept is evaluated by our side.

**Comment by dev-xo** [comment]
Hello @ryan0x44, could you please provide an example of how `remix-webcrypto-cookie-session` could be a patch for our current issue?
- `remix-webcrypto-cookie-session` should be implemented on a Remix App, although `remix-auth-totp` would still suffer from the security vulnerability provided, right?

Would appreciate if we can continue the talk on here.

**Comment by dev-xo** [comment]
Current private discussion about a possible fix based on `jose`.

Sharing here some links in case it could help coming up with a proper fix or a possible implementation:
- Jose [CompactEncrypt](https://github.com/panva/jose/blob/main/docs/classes/jwe_compact_encrypt.CompactEncrypt.md#class-compactencrypt)
- [Algorithm Key Requirements](https://github.com/panva/jose/issues/210)
- [Algorithm Selection Guide](https://github.com/panva/jose/issues/114)

Any insight or help on this case will be much appreciated.

**Comment by dev-xo** [comment]
Not sure if instead of storing sensitive info in the JWT/Cookie, we should store a `sessionId` in the same way Kent C. Dodds does in his own implementation for Epic Stack.

Probably, that would require having a database in the middle, but could be a good solution to look into. Also, I think it will solve the fact that the user could authenticate from another device, just by having the OTP code, something we currently cannot achieve.

Leaving this here as an option to look into, although not sure about the implementation details of it yet.

**Comment by ryan0x44** [comment]
> Hello @ryan0x44, could you please provide an example of how `remix-webcrypto-cookie-session` could be a patch for our current issue?
> 
> * `remix-webcrypto-cookie-session` should be implemented on a Remix App, although `remix-auth-totp` would still suffer from the security vulnerability provided, right?
> 
> Would appreciate if we can continue the talk on here.

Using [remix-webcrypto-cookie-session](https://www.npmjs.com/package/remix-webcrypto-cookie-session) you can effectively mitigate the vulnerability in remix-auth-totp because instead of using Remix's `createCookieSessionStorage` which only signs/verifies cookies, you use the remix-webcrypto-cookie-session `createWebCryptoCookieSessionStorage` function which ensures cookies are encrypted/decrypted.

> Thanks for looking into this, @ryan0x44, also thanks for the DMs on Twitter.
> 
> I shared your proof of concept with @mw10013, and we will be back here to discuss it further. Not sure if you got the time to look into opening a PR, otherwise we will look into it with some guidance from your side.

Unfortunately I don't have capacity but replacing the use of jose's `SignJWT` with `EncryptJWT`, and `jwtVerify` with `jwtDecrypt`, then refactoring the tests appropriately, would like solve for this. Alternatively, you could just put a warning on the README about the fact that the cookie is not encrypted and it is the responsibility of the user to ensure if they're using Cookies for sessions (or any means which exposes the session data to the requesting end user) that the package user ensures they handle the encryption.

**Comment by dev-xo** [comment]
Thanks for the answer @ryan0x44, also no issue in not being able to invest more time into it. 

From my side, I think you already did enough exposing a vulnerability and also taking the time to prove it and sharing some other insights.
- Will try my best to give you proper credits for the whole discovery and the effort put into it.

- - -
Setting a warning and letting people know about this in order for them to handle the situation would be the easy path for us, but not the appropriate one, especially having the tools to fix it.

We are currently looking into `jose`, in order to replace some methods used and into handling the encryption properly. As I said before, any hint or insight will be welcome.

**Comment by dev-xo** [comment]
Changes and updates can be followed from [`jose` branch](https://github.com/dev-xo/remix-auth-totp/tree/jose).
- Huge thanks to @mw10013 for looking into it, as always.

**Comment by dev-xo** [comment]
#57
